blueprint:
  name: Wyświetlenie podglądu kamery
  description: Turn on the primary light when the secondary is turned on and turn off the secondary light when the primary is turned off.
  domain: automation
  input:
    panel:
      name: Panel Fully Kiosk 
      description: Panel Fully Kiosk do użycia
      selector:
        entity:
          domain: media_player
    camera:
      name: Frigate Camera
      description: The name of the camera as defined in your frigate configuration.

source_url: https://github.com/dziobson/Fully-Kiosk-Browser/edit/main/blueprint.yaml
mode: single

trigger:
  platform: mqtt
  topic: frigate/events
  payload: !input camera
  value_template: "{{ value_json['after']['camera'] }}"
variables:
  id: "{{ trigger.payload_json['after']['id'] }}"
  camera: "{{ trigger.payload_json['after']['camera'] }}"
  camera_name: "{{ camera | replace('_', ' ') | title }}"
  object: "{{ trigger.payload_json['after']['label'] }}"
  label: "{{ object | title }}"
  entered_zones: "{{ trigger.payload_json['after']['entered_zones'] }}"
  type: "{{ trigger.payload_json['type'] }}"
condition:
  - "{{ type != 'end' }}"
  
  
action:
  service: fullykiosk.load_url
  data:
    entity_id: media_player.tfmtkaw01232_media_player
    url: http://192.168.1.18:5000/cameras/taras
  mode: single
